baseURL = "/"
languageCode = "en-us"
title = "Vault & OpenShift Demo"
themesDir = "themes"
theme = "hugo-whisper-theme"
relativeURLs = "True"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Demo"
    url = "/demo/"
    weight = 2