baseURL = "/"
languageCode = "en-us"
title = "Vault & OpenShift Demo"
themesDir = "themes"
theme = "hugo-whisper-theme"
relativeURLs = "True"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Demo"
    url = "/demo/"
    weight = 2

[params]
  homepage_button_link = '/demo'
  homepage_button_text = 'Start Tutorial'
  homepage_intro = 'Tutorial showing how to use Vault within OpenShift.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true
  [params.logo]
      standard  = "/images/logo.svg"
