name: markdownlint

on: [push]

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actionshub/markdownlint@main

  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1

  misspell:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - uses: reviewdog/action-misspell@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            locale: "US"